version: "3.9"
services:
  redis:
    image: "redis:alpine"
    networks:
      - backend

  web:
    build: services/frontend
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  reader:
    build: services/reader
    ports:
      - "8081:8081"
    networks:
      - frontend

  writer:
    build: services/writer
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  frontend:
  backend:
